Trestle.resource(:users) do
  remove_action :destroy
  menu do
    item :members, icon: "fa fa-users", priority: 2
  end

  routes do
    post :reset_password, on: :member
  end

  scope :active, default: true do |users|
    users.where(status: :active)
  end

  scope :disabled do |users|
    users.where(status: :disabled)
  end

  scope :suspended do |users|
    users.where(status: :suspended)
  end

  scope :inactive do |users|
    users.where(status: :inactive)
  end

  table do
    column :first_name
    column :last_name
    column :email
    column :phone
    column :status, -> (user) { user.status.titleize }, align: :center
    column :city
    column :country
    column :gender, align: :center
    column :created_at, align: :center
    actions do |toolbar|
      toolbar.show
      toolbar.edit
      toolbar.link "Reset Password",
                   toolbar.instance,
                   admin: toolbar.admin,
                   action: :reset_password,
                   method: :post,
                   icon: "fa fa-key",
                   style: :primary,
                   data: {
                     turbo_method: :post,
                     turbo_confirm: "Send a new password to #{toolbar.instance.email}?"
                   }
    end
  end

  form do |user|
    text_field :first_name
    text_field :last_name
    text_field :email
    text_field :phone
    text_field :address
    text_field :city
    text_field :country
    select :gender, [["Female", "female"], ["Male", "male"], ["Non-binary", "non_binary"], ["Unspecified", "unspecified"]]
    date_field :date_of_birth

    select :status, User.statuses.keys.map { |key| [key.titleize, key] }

    file_field :avatar
    if user.avatar.attached?
      concat content_tag(:div, class: "mt-2") do
        content_tag(:span, "Current avatar: #{user.avatar.filename}")
      end
    end

    if user.persisted?
      concat content_tag(:div, class: "password-tools mt-4") {
        safe_join(
          [
            content_tag(:h4, "Password management"),
            content_tag(:p, "Passwords cannot be edited manually. Send the member a new, autogenerated password instead."),
            link_to(
              "Send reset password email",
              reset_password_users_admin_path(user),
              class: "btn btn-warning",
              method: :post,
              data: { turbo_method: :post, turbo_confirm: "Send a new password to #{user.email}?" }
            ),
          ],
          "\n"
        )
      }
    end
  end

  params do |params|
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :phone,
      :address,
      :country,
      :gender,
      :city,
      :date_of_birth,
      :status,
      :avatar
    )
  end

  controller do
    def destroy
      flash[:error] = "Members cannot be deleted. Update their status instead."
      redirect_to admin.path(:users)
    end

    def reset_password
      user = admin.instance
      Users::PasswordResetService.call(user)
      flash[:message] = "A new password was emailed to #{user.email}."
      redirect_to admin.path(:users, action: :edit, id: user)
    rescue => e
      Rails.logger.error("Password reset failed for user #{user.id}: #{e.message}")
      flash[:error] = "Password reset failed: #{e.message}"
      redirect_to admin.path(:users, action: :edit, id: user)
    end
  end
end

